### PR TITLE
Create reactionsmacros.json

### PR DESCRIPTION
**Pull request by IlGnome**
Reaction macros for reactions.py (formally dwi.py)

### CODE REVIEW

**Comment by linuxdaemon** [comment]
I'd recommend running the `format_json.py` script in the root of the repo when adding new data files, just to ensure they are in the same format as the other JSON files in the project.

**Comment by IlGnome** [comment]
It already uses spaces instead of tabs?

**Comment by linuxdaemon** [comment]
Yes but the indentation and stuff isn't consistent, that script will make sure they are all the same format

**Comment by IlGnome** [comment]
PR was re-done as a single PR instead of two.

**Pull request closed without merging**
