### PR TITLE
Added ice-cream command.

### PR DESCRIPTION
**Pull request by sprintingdev**
Contributions to the content mainly from DavidLuizsHair, PixelPixell, and aflyingflip.

### CODE REVIEW

**Comment by edwardslabs** [comment]
The capitalization in icecream.json is a bit awkward. Can you fix that and push the change?

**Comment by sprintingdev** [comment]
@edwardslabs Not sure what you meant there, the two places I found discrepancies were "Frozen water" and "Sweet potato". Is that what you meant?

**Comment by edwardslabs** [comment]
I don't think the items in flavors and toppings should all be capitalized.

**Comment by sprintingdev** [comment]
Fair enough. Have updated them to make everything lower case.

**Pull request merged**
